name = "sp1-poc"
version = "0.1.0"
defaultTargets = ["sp1-poc"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.17.0"

[[lean_lib]]
name = "Sp1Poc"

[[lean_exe]]
name = "sp1-poc"
root = "Main"
